/** Stable `content_blocks.key` values (locale `ru`). */
export const SITE_CONTENT_KEYS = {
  homeHero: "site.home.hero",
  homeProductShowcases: "site.home.productShowcases",
  homeTrustStrip: "site.home.trustStrip",
  homeRequestCta: "site.home.requestCta",
  homeFaq: "site.home.faq",
  homeMeta: "site.meta.home",
  homeCategories: "site.home.categories",
  homeWhyUs: "site.home.whyUs",
  homeHowItWorks: "site.home.howItWorks",
  homeWhoWeSupply: "site.home.whoWeSupply",
  homeDeliveryCase: "site.home.deliveryCase",
  headerTopNav: "site.header.topNav",
  footerPreCta: "site.footer.preCta",
  footerTrustBar: "site.footer.trustBar",
  footerMain: "site.footer.main",
  aboutMeta: "site.meta.about",
  contactsMeta: "site.meta.contacts",
  aboutCopy: "site.about.copy",
  contactsCopy: "site.contacts.copy",
  pageAbout: "site.page.about",
  pageContacts: "site.page.contacts",
  pageDelivery: "site.page.delivery",
  pageCertificates: "site.page.certificates",
  pagePrivacy: "site.page.privacy",
  pageTerms: "site.page.terms",
} as const;
